#include <Arduino.h> 

String reper[] = {"1 Tropa de Elite",
"2 Cabrobro",
"3 Mulher de Fases",
"4 Proibida pra Mim",
"5 Malandragem",
"6 Reggae Power",
"7 Anjo do Ceu",
"8 Medley",
"9 Cerveja de Garrafa",
"10 Fica do meu Lado",
"11 ela vai voltar",
"12 So Por Hoje",
"13 M Mundo",
"14 Regina lets go",
"15 Me Lambe",
"16 Que Pais e Este",
"17 So os Loucos Sabem",
"18 Tempo Perdido",
"19 Deixe-me Ir",
"20 Outro Lugar",
"21 Samba Makossa",
"22 Jack Tequila",
"23 Naticongo",
"24 Zoio de Lula",
"25 Quero ser Feliz",
"26 Paulinha/Folha/Sabado",
"27 Pisando Descalço",
"28 Envolvidao",
"29 O Sol",
"30 Ceu Azul",
"31 Minuto p o Fim",
"32 Robocop Gay",
"33 Pontes Indestrutiveis",
"34 Anna Julia",
"35 Pescador",
"36 Menina Linda",
"37 Papo Reto",
"38 Eu quero ver o oco",
"39 Killing the name"};
